### ISSUE TITLE
key file may be password protected

### ISSUE THREAD

**Issue by mobedi** [Thorium/EntityFramework.BulkInsert#1]
When I try to open the solution, it asks for a connection to `Team Foundation Server` and then I receive the error that says:

> Cannot import the following key file: efbulkinsert.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_09E1AEBCD4A9E1E1 EntityFramework.BulkInsert.Net40

Therefore I am unable to build the solution.

**Comment by Thorium** [comment]
Yes, I don't have the access to the original key file so I guess you have to create your own:

Open the project in the Visual Studio, go Solution Explorer and right click over the project file (for each project) and select:
-> Properties
-> Signing
-> Choose a strong name key file: `<New...>`
Then create a new key file or re-use the one you just created. That should be ok.
